$(document).ready(function(){
  $('#section1').show();
    $('#section2').hide();
    $('#section3').hide();
});

$(document).ready(function(){
    $("#step1").click(function(){
         $("#section1").hide();
        $("#section2").show();
        $('#section3').hide();
    }); 
    $("#step2l").click(function(){
         $("#section1").show();
        $("#section2").hide();
        $('#section3').hide();
    }); 
    $("#step2r").click(function(){
         $("#section1").hide();
        $("#section2").hide();
        $('#section3').show();
    }); 
    $("#step3").click(function(){
         $("#section1").hide();
        $("#section2").show();
        $('#section3').hide();
    }); 
});