$(document).ready(function(){
                $('#app1').click(function(){
                    $('#app1').attr('src','../images/fillStar-clipart.jpg');
                    $('#app2,#app3,#app4,#app5').attr('src','../images/emptyStar-clipart.png');
                    $('#appStar').val(1);
                }); 
                $('#app2').click(function(){
                    $('#app1,#app2').attr('src','../images/fillStar-clipart.jpg');
                    $('#app3,#app4,#app5').attr('src','../images/emptyStar-clipart.png');
                    $('#appStar').val(2);
                }); 
                $('#app3').click(function(){
                    $('#app1,#app2,#app3').attr('src','../images/fillStar-clipart.jpg');
                    $('#app4,#app5').attr('src','../images/emptyStar-clipart.png');
                    $('#appStar').val(3);
                }); 
                $('#app4').click(function(){
                    $('#app1,#app2,#app3,#app4').attr('src','../images/fillStar-clipart.jpg');
                    $('#app5').attr('src','../images/emptyStar-clipart.png');
                    $('#appStar').val(4);
                }); 
                $('#app5').click(function(){
                    $('#app1,#app2,#app3,#app4,#app5').attr('src','../images/fillStar-clipart.jpg');
                    $('#appStar').val(5);
                }); 
                $('#shopkeeper1').click(function(){
                    $('#shopkeeper1').attr('src','../images/fillStar-clipart.jpg');
                    $('#shopkeeper2,#shopkeeper3,#shopkeeper4,#shopkeeper5').attr('src','../images/emptyStar-clipart.png');
                    $('#shopkeeperStar').val(1);
                }); 
                $('#shopkeeper2').click(function(){
                    $('#shopkeeper1,#shopkeeper2').attr('src','../images/fillStar-clipart.jpg');
                    $('#shopkeeper3,#shopkeeper4,#shopkeeper5').attr('src','../images/emptyStar-clipart.png');
                    $('#shopkeeperStar').val(2);
                }); 
                $('#shopkeeper3').click(function(){
                    $('#shopkeeper1,#shopkeeper2,#shopkeeper3').attr('src','../images/fillStar-clipart.jpg');
                    $('#shopkeeper4,#shopkeeper5').attr('src','../images/emptyStar-clipart.png');
                    $('#shopkeeperStar').val(3);
                }); 
                $('#shopkeeper4').click(function(){
                    $('#shopkeeper1,#shopkeeper2,#shopkeeper3,#shopkeeper4').attr('src','../images/fillStar-clipart.jpg');
                    $('#shopkeeper5').attr('src','../images/emptyStar-clipart.png');
                    $('#shopkeeperStar').val(4);
                }); 
                $('#shopkeeper5').click(function(){
                    $('#shopkeeper1,#shopkeeper2,#shopkeeper3,#shopkeeper4,#shopkeeper5').attr('src','../images/fillStar-clipart.jpg');
                    $('#shopkeeperStar').val(5);
                });
                $('#product1').click(function(){
                    $('#product1').attr('src','../images/fillStar-clipart.jpg');
                    $('#product2,#product3,#product4,#product5').attr('src','../images/emptyStar-clipart.png');
                    $('#productStar').val(1);
                }); 
                $('#product2').click(function(){
                    $('#product1,#product2').attr('src','../images/fillStar-clipart.jpg');
                    $('#product3,#product4,#product5').attr('src','../images/emptyStar-clipart.png');
                    $('#productStar').val(2);
                }); 
                $('#product3').click(function(){
                    $('#product1,#product2,#product3').attr('src','../images/fillStar-clipart.jpg');
                    $('#product4,#product5').attr('src','../images/emptyStar-clipart.png');
                    $('#productStar').val(3);
                }); 
                $('#product4').click(function(){
                    $('#product1,#product2,#product3,#product4').attr('src','../images/fillStar-clipart.jpg');
                    $('#product5').attr('src','../images/emptyStar-clipart.png');
                    $('#productStar').val(4);
                }); 
                $('#product5').click(function(){
                    $('#product1,#product2,#product3,#product4,#product5').attr('src','../images/fillStar-clipart.jpg');
                    $('#productStar').val(5);
                }); 
            });